import { activeDecisions, byId, type LoadedDecision, type Store } from "./store.js";
import { GLOBAL_AREA } from "./schema.js";

export const INDEX_HEADER = "<!-- Generated by `lore index`. Do not edit by hand. -->";

/**
 * Render `INDEX.md`.
 *
 * This file is read on every agent session, so it is the one place where every
 * byte has to earn its keep. Three consequences:
 *
 * - Only `active` decisions appear. Superseded ones stay on disk and are reachable
 *   through `lore list --status superseded`; what stops an agent reviving them is
 *   the `## Rejected` section of the decision that replaced them, not a line here.
 * - A line is just id + what. No path (ids are unique, so `.lore/*'/<id>.md` finds
 *   it) and no status (everything here is active).
 * - A decision with several scopes is written out once, under its first area. The
 *   others get one grouped cross-reference line, not a full copy each.
 */
export function renderIndex(store: Store): string {
	const active = activeDecisions(store).sort(byId);
	const lines: string[] = [INDEX_HEADER, "", "# Lore index", ""];

	if (active.length === 0) {
		lines.push("No decisions recorded yet. `lore add` writes the first one.", "");
		return lines.join("\n");
	}

	lines.push(
		`${active.length} active ${active.length === 1 ? "decision" : "decisions"}. Open the full file at \`.lore/*/<id>.md\`.`,
		"",
	);

	const areas = areasInPlay(active);
	for (const area of areas) {
		const own = active.filter((loaded) => loaded.decision.frontmatter.scope[0] === area);
		const alsoHere = active.filter(
			(loaded) =>
				loaded.decision.frontmatter.scope[0] !== area &&
				loaded.decision.frontmatter.scope.includes(area),
		);

		lines.push(area === GLOBAL_AREA ? `## ${area}  (always read)` : `## ${area}`);
		for (const loaded of own) {
			lines.push(`- \`${loaded.decision.frontmatter.id}\` — ${loaded.decision.frontmatter.what}`);
		}
		if (alsoHere.length > 0) {
			const ids = alsoHere.map((loaded) => `\`${loaded.decision.frontmatter.id}\``).join(", ");
			lines.push(`> Also applies here: ${ids}`);
		}
		lines.push("");
	}

	return lines.join("\n");
}

/** Every area mentioned by an active decision, `global` first then alphabetical. */
function areasInPlay(active: LoadedDecision[]): string[] {
	const seen = new Set<string>();
	for (const loaded of active) {
		for (const area of loaded.decision.frontmatter.scope) seen.add(area);
	}
	return [...seen].sort((a, b) => {
		if (a === GLOBAL_AREA) return -1;
		if (b === GLOBAL_AREA) return 1;
		return a.localeCompare(b);
	});
}
