import assert from "node:assert/strict";
import { readFileSync, mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import { test } from "node:test";
import { invoke, makeRepo, type Fixture } from "./helpers.js";

const REPO: Record<string, Fixture> = {
	"strict-ts": { what: "Compile with TypeScript strict", scope: ["global"] },
	"postgres-over-dynamo": {
		what: "Use Postgres as the primary store, not DynamoDB",
		scope: ["backend", "data"],
		paths: ["packages/api/**", "packages/ingest/**"],
	},
	"raw-sql-no-orm": { what: "Write SQL by hand, no ORM", scope: ["backend"] },
	"trpc-over-rest": { what: "Expose the API over tRPC, not REST", scope: ["api", "frontend"] },
	"rest-with-openapi": {
		what: "Expose the API as REST with an OpenAPI spec",
		scope: ["api"],
		status: "superseded",
		superseded_by: "trpc-over-rest",
	},
};

test("list shows only active decisions by default", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["list"]);
	assert.equal(result.code, 0);
	assert.match(result.out, /postgres-over-dynamo/);
	assert.doesNotMatch(result.out, /rest-with-openapi/);
});

test("list --status any includes superseded, labelled", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["list", "--status", "any"]);
	assert.match(result.out, /rest-with-openapi.*\(superseded\)/);
});

test("list --scope filters on any area, not just the first", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["list", "--scope", "data"]);
	assert.match(result.out, /postgres-over-dynamo/);
	assert.doesNotMatch(result.out, /raw-sql-no-orm/);
});

test("list --json emits parseable records with their file path", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["list", "--json"]);
	const rows = JSON.parse(result.out) as { id: string; file: string }[];
	assert.ok(rows.every((row) => row.file.startsWith(".lore/")));
	assert.ok(rows.some((row) => row.id === "trpc-over-rest"));
});

test("list rejects an unknown --status instead of silently listing everything", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["list", "--status", "vigente"]);
	assert.equal(result.code, 2);
	assert.match(result.err, /--status must be one of/);
});

test("show prints the file byte for byte", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["show", "raw-sql-no-orm"]);
	assert.equal(result.code, 0);
	assert.equal(result.out, readFileSync(join(root, ".lore/backend/raw-sql-no-orm.md"), "utf8"));
});

test("show on a missing id exits 1 and suggests near matches", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["show", "postgres"]);
	assert.equal(result.code, 1);
	assert.match(result.err, /did you mean: postgres-over-dynamo/);
});

test("for matches a governed path and names the rejected options", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["for", "packages/api/server.ts"]);
	assert.equal(result.code, 0);
	assert.match(result.out, /postgres-over-dynamo/);
	assert.match(result.out, /Already rejected: La otra opción/);
});

test("for is completely silent when nothing matches, and exits 1", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["for", "web/index.html"]);
	assert.equal(result.code, 1);
	assert.equal(result.out, "", "a hook running on every edit cannot print on a miss");
	assert.equal(result.err, "");
});

test("for stays silent about unrelated broken files", async () => {
	const root = makeRepo(REPO);
	writeFileSync(join(root, ".lore/backend/broken.md"), "no frontmatter here\n", "utf8");
	const result = await invoke(root, ["for", "web/index.html"]);
	assert.equal(result.code, 1);
	assert.equal(result.err, "");

	const listed = await invoke(root, ["list"]);
	assert.match(listed.err, /run `lore check`/, "other commands should still warn");
});

test("for accepts an absolute path", async () => {
	const root = makeRepo(REPO);
	const result = await invoke(root, ["for", join(root, "packages/ingest/worker.ts")]);
	assert.equal(result.code, 0);
	assert.match(result.out, /postgres-over-dynamo/);
});

test("for ignores superseded decisions", async () => {
	const root = makeRepo({
		old: {
			what: "Old thing",
			scope: ["backend"],
			paths: ["src/**"],
			status: "superseded",
			superseded_by: "new",
		},
		new: { what: "New thing", scope: ["backend"] },
	});
	assert.equal((await invoke(root, ["for", "src/a.ts"])).code, 1);
});

test("index groups by area, puts global first, and cross-references once", async () => {
	const root = makeRepo(REPO);
	assert.equal((await invoke(root, ["index"])).code, 0);
	const index = readFileSync(join(root, ".lore/INDEX.md"), "utf8");

	assert.match(index, /^<!-- Generated by `lore index`\. Do not edit by hand\. -->/);
	assert.ok(index.indexOf("## global") < index.indexOf("## api"), "global must come first");
	assert.match(index, /## global {2}\(always read\)/);

	// The full line lives under the first scope; other areas get one grouped line.
	assert.match(index, /## backend\n- `postgres-over-dynamo` — Use Postgres/);
	assert.match(index, /## data\n> Also applies here: `postgres-over-dynamo`/);
	assert.equal(index.match(/Use Postgres as the primary store/g)?.length, 1, "no full duplicates");

	assert.doesNotMatch(index, /rest-with-openapi/, "superseded decisions stay out of the index");
	assert.match(index, /^4 active decisions\./m);
});

test("index --check reports staleness without writing", async () => {
	const root = makeRepo(REPO);
	assert.equal((await invoke(root, ["index"])).code, 0);
	assert.equal((await invoke(root, ["index", "--check"])).code, 0);

	mkdirSync(join(root, ".lore/ops"), { recursive: true });
	writeFileSync(
		join(root, ".lore/ops/deploy-on-merge.md"),
		readFileSync(join(root, ".lore/backend/raw-sql-no-orm.md"), "utf8")
			.replace("id: raw-sql-no-orm", "id: deploy-on-merge")
			.replace("scope: [backend]", "scope: [ops]"),
		"utf8",
	);

	const before = readFileSync(join(root, ".lore/INDEX.md"), "utf8");
	const stale = await invoke(root, ["index", "--check"]);
	assert.equal(stale.code, 1);
	assert.match(stale.err, /out of date/);
	assert.equal(
		readFileSync(join(root, ".lore/INDEX.md"), "utf8"),
		before,
		"--check must not write",
	);
});

test("an empty lore renders an index that says so", async () => {
	const root = makeRepo({});
	await invoke(root, ["index"]);
	assert.match(readFileSync(join(root, ".lore/INDEX.md"), "utf8"), /No decisions recorded yet/);
});

test("the inbox is invisible to every read command", async () => {
	const root = makeRepo(REPO, { inbox: ["some-proposal"] });
	await invoke(root, ["index"]);

	const index = readFileSync(join(root, ".lore/INDEX.md"), "utf8");
	assert.doesNotMatch(index, /some-proposal/);
	assert.doesNotMatch((await invoke(root, ["list", "--status", "any"])).out, /some-proposal/);
	assert.equal((await invoke(root, ["show", "some-proposal"])).code, 1);
	assert.doesNotMatch(index, /## inbox/);
});

test("commands outside a lore repo explain what to run", async () => {
	const result = await invoke("/", ["list"]);
	assert.equal(result.code, 2);
	assert.match(result.err, /Run `lore init` first/);
});

test("the loader reports a file whose id does not match its name", async () => {
	const root = makeRepo(REPO);
	writeFileSync(
		join(root, ".lore/backend/misnamed.md"),
		readFileSync(join(root, ".lore/backend/raw-sql-no-orm.md"), "utf8"),
		"utf8",
	);
	assert.match((await invoke(root, ["list"])).err, /2 problems/);
});
